Yaya/custom recycler view+bottom nav bar+favorites page+expanded list+refresh button+Search functions
GrinnellAppDev/Events-Android pull request #13
Opened 2018-08-24 04:02 UTC by lamsalab

I think this is a minimum viable product. I have tested it on my phone and it works fine. I still have more to implement, which will be shipped periodically unlike this one. Let me know what I have to change before we make a merge.

2018-10-07 19:06 UTC, mattorib requested changes
Looks good for the most part! The map needs an authentication token, which you should be able to produce, and the files should be organized a little more (ie. adapters, activities, models, etc. in individual folders).

2018-10-07 19:06 UTC, mattorib commented on app/src/main/java/edu/grinnell/appdev/events/FragmentMap.java
> +        mapView.getMapAsync(new OnMapReadyCallback() {
There seems to be an authentication issue which causes the map to not work at all.

2018-10-07 19:06 UTC, mattorib commented on app/src/main/java/edu/grinnell/appdev/events/AsyncParser.java
> +    private String organizer;
Unused variable

2018-10-07 19:06 UTC, mattorib commented on app/src/main/java/edu/grinnell/appdev/events/AsyncParser.java
> +        int count = 0;
Unused variable

2018-10-07 19:06 UTC, PsychicNoodles commented on app/src/main/java/edu/grinnell/appdev/events/onParseComplete.java
>  /**
Classes and interfaces should be named with upper camelcase, so the first letter should be capitalized.

2018-10-14 18:50 UTC, lamsalab commented on app/src/main/java/edu/grinnell/appdev/events/FragmentMap.java
> +        mapView.getMapAsync(new OnMapReadyCallback() {
I tested it and it seems to work on multiple devices.

2019-01-27 19:34 UTC, zoerosemarie approved these changes
Looks good!

2019-01-27 19:36 UTC, mattorib approved these changes

2019-01-27 19:37 UTC, merged